/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.kit2512.oop_sms.presentation.views.InfoView;

import dev.kit2512.oop_sms.domain.entities.ResultEntity;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author h
 */
public class StudentResultPanel extends javax.swing.JPanel {
    private DefaultTableModel tableModel;
    
    private List<ResultEntity> results;
    
    /**
     * Creates new form StudentResultPanel
     */
    public StudentResultPanel(List<ResultEntity> results) {
        this.results = results;
        initComponents();
        this.setAlignmentX(Component.LEFT_ALIGNMENT);
        this.jScrollPane1.setAlignmentX(Component.LEFT_ALIGNMENT);
        this.resultTable.setAlignmentX(Component.LEFT_ALIGNMENT);
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        editScoreBtn = new javax.swing.JButton();
        removeResultBtn = new javax.swing.JButton();
        updateResultBtn = new javax.swing.JButton();
        updateResultBtn1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(346, 205));
        setMinimumSize(new java.awt.Dimension(200, 48));
        setPreferredSize(new java.awt.Dimension(346, 200));
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        resultTable.setPreferredSize(new java.awt.Dimension(216, 448));
        resultTable.getTableHeader().setResizingAllowed(false);
        resultTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(resultTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEADING);
        flowLayout1.setAlignOnBaseline(true);
        jPanel1.setLayout(flowLayout1);

        editScoreBtn.setText("Add result");
        jPanel1.add(editScoreBtn);

        removeResultBtn.setText("Remove result");
        jPanel1.add(removeResultBtn);

        updateResultBtn.setText("Update result");
        jPanel1.add(updateResultBtn);

        updateResultBtn1.setText("Calculate GPA");
        jPanel1.add(updateResultBtn1);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    private void initTable() {
        this.tableModel = new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        };
        setTableModelData();
    }
    
    private void setTableModelData() {
        for (ResultEntity result : results) {
            final ArrayList<Object> row = new ArrayList<>();
            row.add(result.getResultId());
            row.add(result.getSubject().getSubjectName());
            row.add(result.getResultScore());
            tableModel.addRow(row.toArray());
        }
        resultTable.setModel(tableModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editScoreBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeResultBtn;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton updateResultBtn;
    private javax.swing.JButton updateResultBtn1;
    // End of variables declaration//GEN-END:variables
}
