/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.kit2512.oop_sms.presentation.views.InfoView;

import dev.kit2512.oop_sms.domain.entities.StudentEntity;
import java.awt.Component;

/**
 *
 * @author h
 */
public class StudentInfoPanel extends javax.swing.JPanel {
    private final StudentEntity student;
    
    /**
     * Creates new form StudentInformationView
     */
    public StudentInfoPanel(StudentEntity studentEntity) {
        initComponents();
        this.student = studentEntity;
        this.idLb.setText(student.getStudentFullId());
        this.classLb.setText(student.getFullClassLetter());
        this.majorLb.setText(student.getMajor().getName());
        this.yoAdmissionLb.setText(student.getYearOfAdmission().toString());

        this.setAlignmentX(Component.RIGHT_ALIGNMENT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idLb = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        yoAdmissionLb = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        classLb = new javax.swing.JLabel();
        majorLb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();

        jLabel1.setText("Student ID");

        idLb.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        idLb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        idLb.setText("CT050222");
        idLb.setToolTipText("");

        jLabel3.setText("Year of adminsion");

        yoAdmissionLb.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        yoAdmissionLb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        yoAdmissionLb.setText("2020");
        yoAdmissionLb.setToolTipText("");

        jLabel5.setText("Class");

        classLb.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        classLb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        classLb.setText("CT5B");
        classLb.setToolTipText("");

        majorLb.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        majorLb.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        majorLb.setText("Công nghệ thông tin");
        majorLb.setToolTipText("");

        jLabel8.setText("Major");

        editBtn.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                        .addComponent(yoAdmissionLb))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                        .addComponent(classLb))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(majorLb))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(editBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idLb)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(yoAdmissionLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(classLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(majorLb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel classLb;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel idLb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel majorLb;
    private javax.swing.JLabel yoAdmissionLb;
    // End of variables declaration//GEN-END:variables
}
