/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.kit2512.oop_sms.presentation.views.InfoView;

import dev.kit2512.oop_sms.App;
import dev.kit2512.oop_sms.domain.entities.UserEntity;
import dev.kit2512.oop_sms.presentation.views.UpdatePasswordView;
import java.awt.Component;
import javax.swing.*;

/**
 *
 * @author h
 */
public class UserInfoPanel extends javax.swing.JPanel {
    final UserEntity userEntity;

    /**
     * Creates new form UserInformationView
     * @param userEntity
     */
    public UserInfoPanel(UserEntity userEntity) {
        this.userEntity = userEntity;
        initComponents();
        this.usernameLabel.setText(userEntity.getUsername());
        this.fullNameLabel.setText(userEntity.getFullName());
        this.addressLabel.setText(userEntity.getUserAddress());
        this.dateOfBirthLabel.setText(userEntity.getUserDateOfBirthString());
        this.emailLabel.setText(userEntity.getUserEmail());
        this.roleLabel.setText(userEntity.getUserRole().toString());
        this.phoneNumberLabel.setText(userEntity.getUserPhone());
        this.genderLabel.setText(userEntity.getUserGender() ? "Female" : "Male");
        final UserEntity.UserRole userRole = App.appGraph.getAuthenticationRepository().getCurrentUser().getUserRole();
        if (userRole == UserEntity.UserRole.STUDENT) {
           this.resetPasswordBtn.setVisible(false);
        }
        
        this.setAlignmentX(Component.RIGHT_ALIGNMENT);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roleLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        deleteUserBtn = new javax.swing.JButton();
        resetPasswordBtn = new javax.swing.JButton();
        updaetInfoBtn = new javax.swing.JButton();
        updatePasswordBtn = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(610, 205));

        roleLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roleLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        roleLabel.setText("Admin");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailLabel.setText("dannamdinh49@gmail.com");

        genderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        genderLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        genderLabel.setText("Male");

        dateOfBirthLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateOfBirthLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dateOfBirthLabel.setText("01/01/2002");

        jLabel3.setText("Full name");

        fullNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        fullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        fullNameLabel.setText("Nguyễn Hữu Hùng");

        jLabel14.setText("Phone");

        jLabel1.setText("Username");

        jLabel5.setText("Date of birth");

        jLabel15.setText("Role");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        usernameLabel.setText("demo1234");

        addressLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        addressLabel.setText("Huyện Nghĩa Hưng, tỉnh Nam Định");

        jLabel11.setText("Email");

        jLabel9.setText("Address");

        jLabel7.setText("Gender");

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        phoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        phoneNumberLabel.setText("0364011846");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fullNameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateOfBirthLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(genderLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(addressLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(phoneNumberLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roleLabel)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fullNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateOfBirthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(genderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(phoneNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(roleLabel))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        deleteUserBtn.setText("Delete user");
        deleteUserBtn.setMaximumSize(new java.awt.Dimension(141, 23));
        deleteUserBtn.setMinimumSize(new java.awt.Dimension(141, 23));
        deleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtnActionPerformed(evt);
            }
        });
        jPanel2.add(deleteUserBtn);

        resetPasswordBtn.setText("Reset password");
        resetPasswordBtn.setMaximumSize(new java.awt.Dimension(141, 23));
        resetPasswordBtn.setMinimumSize(new java.awt.Dimension(141, 23));
        jPanel2.add(resetPasswordBtn);

        updaetInfoBtn.setText("Update information");
        updaetInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updaetInfoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updaetInfoBtn);

        updatePasswordBtn.setText("Update password");
        updatePasswordBtn.setMaximumSize(new java.awt.Dimension(141, 23));
        updatePasswordBtn.setMinimumSize(new java.awt.Dimension(141, 23));
        updatePasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePasswordBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updatePasswordBtn);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updaetInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updaetInfoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updaetInfoBtnActionPerformed

    private void deleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtnActionPerformed
        final Integer selected = JOptionPane.showConfirmDialog(this, "Do you want to deleted this user?\nAll data will be lost");
        if (selected == JOptionPane.YES_OPTION) {
            App.appGraph.getStudentListModel().setRemovingStudentId(userEntity.getUserId());
            App.appGraph.getInfoController().elementClosingChanged(true);
            App.appGraph.getStudentListController().elementFetchingStudentListChanged(true);
        }
    }//GEN-LAST:event_deleteUserBtnActionPerformed

    private void updatePasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePasswordBtnActionPerformed
        final UpdatePasswordView updatePasswordView = App.appGraph.getUpdatePasswordView();
        updatePasswordView.getData(userEntity.getUserId());
        updatePasswordView.setModal(true);
        updatePasswordView.setVisible(true);
    }//GEN-LAST:event_updatePasswordBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JButton deleteUserBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton resetPasswordBtn;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton updaetInfoBtn;
    private javax.swing.JButton updatePasswordBtn;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
